name: pinboard
description: A library that provides a nice interface to communicate with the Pinboard API.
version: 1.0.0
homepage: https://github.com/dstaley/pinboard-dart
author: Dylan Staley <staley.dylan@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.1.6

dev_dependencies:
  test: ^1.0.0
  coverage: ^0.12.3
  duvet: ^0.0.1
